apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: {{ include "sdp-oauth2-proxy.name" . }}
    helm.sh/chart: {{ include "sdp-oauth2-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s-app: {{ .Values.labels.k8s_app }}
spec:
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    k8s-app: {{ .Values.labels.k8s_app }}
